include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: totem_right
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
